### ISSUE TITLE
Add Ore Generation Configuration

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#26]
Cluster Size
Frequency
High/Low

Diamonds spawn on top/bottom, might want to set this for all?

**Comment by IronyAtFive** [comment]
Maybe juste the top for diamonds? As logicaly the top bedrock of nether is the floor bedrock of overworld. So there would make the most sense. And the bottom of the Nether is sea of lava, so normally diamond would not exist there. For frequency and all, that would be like the custom world gen. It would be nice

**Comment by renevo** [comment]
I do like the idea of only having diamonds at the top of the Nether. I am actually pretty happy with the ore generation for emeralds, rare enough to be happy when you find one, but not so rare you can never find them.

I really need to integrate with the ore generation JEI plugin so this is more apparent.

**Comment by IronyAtFive** [comment]
Ya, that should be high on to-do list. Cause if peoples use other mod and see they are not compatible, it will be deceiving

**Comment by novasolarius** [comment]
First of all, the bottom of the Nether isn't the same as the lava sea. There's plenty of solid netherrack to be found below it, complete with lava-free caves. Secondly, I'm going to leave out or simplify a lot of science here, but prepare for a long post or skip to the summary.

Regarding diamond spawning near the bottom of the Nether, I would just like to point out that the formation is plausible. Lava, as we all know, is both hot and bloody heavy, and the Nether, if we think of it as part of the same world as the Overworld, is located an unknown distance from the surface, thus possibly quite close to the core of what can be assumed is a planet. These factors would provide the pressure and heat required to form diamond.

Diamonds can be found all over the Overworld, relatively close to the surface. The way I see it, since diamonds normally arrive near the surface by means of volcanic eruptions, they have been deposited there in one of three ways. One is very frequent eruptions in the Nether, which would result in a fairly even distribution through the Nether, though with higher amounts near the top and bottom.

Another is occasional lava floods, and those would need to be substantial enough to reach the ceiling and cover the lower levels of the Overworld in boiling stone. In this case, the distribution should favour the bottom, but diamond would need to be found everywhere. Finally, they could have been deposited by activity in the space between the Nether and the Overworld, at which point the Nether should be mostly liquid due to the incredibly vicinity to the core.

Option three makes little sense, mostly since the Nether is solid. Disregarding the ocean, of course. Option two is more likely, but if the Overworld had been flooded, most of the lava should've cooled down. The frequency of lava pits makes this unlikely. Alternatively, the flood could've been recent, but then the Nether would still be covered in lava to an extend not found there.

Thus, I consider the first option the most likely one. Diamonds would have been left embedded in the Overworld's rock by frequent geysers of magma, resulting in the lava bubbles we all love to hate. They would also explain the lavafalls in the Nether, simply places where lava is seeping through the stone following an eruption. Thus diamond should occur everywhere. Since they form near the bottom, they should be most abundant there, and since there is more solid material for them to get stuck in in the ceiling, they should be more abundant there as well.

**Summary**: I think diamonds should be found everywhere, but rarely. They should have increased density near the top of the Nether and even more so near the bottom. See post for reasoning. Thank you for reading.

**Comment by renevo** [comment]
Thanks for that writeup @Nova001Sol :+1:
