### ISSUE TITLE
Nether Village

### ISSUE THREAD

**Issue by renevo** [RenEvo/nethercore#8]
Simple nether wart farm and farm house, use the custom blocks from the mod, single building "village".
- [ ] Farm Section
- [ ] House
- [ ] Door
- [ ] Villager
- [ ] Trades

**Comment by renevo** [comment]
Was thinking that the trades could be mod items and nether items.

e.g.

Nether Wart in/out
Blaze Rod in/out
Magma Cream in/out
Ghast Tear in/out

etc...

**Comment by renevo** [comment]
Not 100% sold on this one.

**Comment by IronyAtFive** [comment]
I would actually love it! Having a normal pigmen mobs. 
The ground could be nethergrowth, but could led to unwanted expansion. 
The windows should be netherstone wall because of ghast fireball. 
The farms could maybe be covered with a simple roof for simple protection. 
The trade could be a good source of NetherGrowth, as I can't find a way to get my hand on it. 
You could add a NetherStone door, with blast resistance but opening like wooden door.
The paths could be out of soul sand, or simply gravel.

This would make the Nether WAAYYYY more interesting! Maybe you could work on nether crops that grow on tilled NetherGrowth and that growth faster when lava is near the block (as overworld crops need water). The trade could also include some nether saplings, which would grow tree that you can't find without trading for the sapling.
If you want a trade system, don't go for mob drops to get from trade, as villagers won't fight but will want help to gather thoses materials.

**Comment by IronyAtFive** [comment]
Also, maybe Pigmen Villagers could be attacked by Zombie Pigmens, but not other mobs. That would get the player to choose between defending from Zombie Pigmen for having trade, or letting them get killed to save trouble of being swarmed. 
You could also do a torch recipe that use glowstone and would be found naturally in the Nether Village house. To give a protection like iron golem in overworld, it would need a path of NetherBrick (or like that) that go around town and a ground of NetherGrowth (the path that is around protect from huge expansion of NetherGrowth). That would be just for village with big enough population.
Pigmen should be fire and lava resistant like Zombie Pigmen, to protect from NetherGrowth flame.
